const DEFAULT_SETTINGS = {
  id: 'main',
  siteName: 'الهيف للخدمات العقارية',
  siteDescription: 'مكتب عقاري اكتروني — خبرة وثقة في التسويق والخدمات العقارية',
  logoUrl: '/images/logo-alheef.png',
  faviconUrl: '/assets/favicon.png',
  heroTitle: 'الهيف للخدمات العقارية',
  heroSubtitle: 'مكتب عقاري اكتروني',
  heroImage: 'https://images.unsplash.com/photo-1600585154340-be6162a9a2c9?w=1920&q=85',
  heroMobileImage: 'https://images.unsplash.com/photo-1600585154340-be6162a9a2c9?w=960&q=80',
  whatsappNumber: '966500000000',
  email: 'info@alheef.com',
  phone: '050 000 0000',
  address: 'الرياض، المملكة العربية السعودية',
  googleMap: '',
  instagram: 'https://instagram.com/alheef',
  twitter: 'https://x.com/alheef',
  snapchat: '',
  tiktok: '',
  primaryColor: '#000000',
  secondaryColor: '#C5A46D',
  footerText: '© الهيف للخدمات العقارية — جميع الحقوق محفوظة',
  aboutText:
    'مكتب عقاري اكتروني يقدم خدمات التسويق والبيع وإدارة الأملاك بمعايير احترافية راقية.',
  visionText: 'أن نكون الخيار الأول للخدمات العقارية الراقية في المملكة.',
  missionText: 'تقديم تجربة عقارية موثوقة وشفافة تليق بتطلعات عملائنا.',
  updatedAt: new Date().toISOString(),
};

module.exports = { DEFAULT_SETTINGS };
